import {
    onInstall,
    onOpen,
    openSidebar,
} from './ui';

import {
    getUserEmail,
    getUserData,
    getInitData,
} from './sheets';

import {
    createGoogleDoc,
    getGoogleDocNamesByIds,
    getGoogleDocPlainText,
    getPreviewRowValues,
    preflightGenerateLOIs,
    generateLOIChunk,
    queueEnsureSheet,
    queueExists,
    getSendSummary,
    sendNextBatch,
    queueList,
    queueStatus,
    getSheetNames,
    getActiveSheetName,
    queueClearAll,
    queueUpdateStatus,
    showSendQueueTab,
    highlightQueueRow,
    loiEnsureRootFolder,
    loiEnsureFolders,
    queueDeleteDocsSimple,
    resetLoiUserPropsDev,
    getLoiUserPropsDev,
    queuePurgeSentAndCompact,
    setLoiDateKeyToYesterdayDev,
    queueDeleteDocsByIds,
    deleteJobsInQueueGivenRows,
    getGmailRemaining,
} from './docs';

// Public functions must be exported as named exports
export {
    onInstall,
    onOpen,
    openSidebar,
    createGoogleDoc,
    getUserEmail,
    getUserData,
    getInitData,
    getGoogleDocNamesByIds,
    getGoogleDocPlainText,
    getPreviewRowValues,
    preflightGenerateLOIs,
    generateLOIChunk,
    queueEnsureSheet,
    queueExists,
    getSendSummary,
    sendNextBatch,
    queueList,
    queueStatus,
    getSheetNames,
    getActiveSheetName,
    queueClearAll,
    queueUpdateStatus,
    showSendQueueTab,
    highlightQueueRow,
    loiEnsureRootFolder,
    loiEnsureFolders,
    queueDeleteDocsSimple,
    resetLoiUserPropsDev,
    getLoiUserPropsDev,
    queuePurgeSentAndCompact,
    setLoiDateKeyToYesterdayDev,
    queueDeleteDocsByIds,
    deleteJobsInQueueGivenRows,
    getGmailRemaining,
};
