module.exports = {
    DAYS: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    MONTHS: ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
    ],
    SERVER_ERROR_MSG: "An error occurred while connecting to the server. Please contact support at tidisventures@gmail.com.",
    PAYMENT_ERROR_MSG: "An error occurred with your payment. Please try again or contact support at tidisventures@gmail.com.",
    VIEW_ACT_CTA: 'See pricing.',
    LIGHT_RED_BERRY: "#FFCBCB",
    LIGHT_GREEN: "#93c47d",
    DARK_RED_BERRY: "#5f2120",
    SETTINGS_SHEETNAME: `Settings`,
    ANA_RESULTS_SHEETNAME: String.fromCodePoint(0x1F4CB) + 'Analysis results',
    ANALYSIS_MODES: [
        '',
        'Long term rental property',
        'Short term rental property',
        'Fix and flip',
    ],
    ANA_OUTPUT_RANGES: {
        LTR: {
            startCol: "F",
            endCol: "AB"
        },
        STR: {
            startCol: "F",
            endCol: "AM"
        },
        FNF: {
            startCol: "C",
            endCol: "V"
        },
    },
    SETTINGS: {
        VALUES_RANGE: 'B3:B53',
        VALUES: {
            PURCHASE: [
                ['20'],
                ['0'],
                ['3000'],
                ['1000'], // est upfront cost
                ['0'], // other lender costs
            ],
            LOAN: [
                ['5'],
                ['0'],
                ['30'],
            ],
            EXPENSES: [
                ['1'],
                ['0'],
                ['1'],
                ['2000'],
                ['5'],
                ['0'],
                ['5'],
                ['0'],
                ['10'],
                ['0'],
                ['0'],
                ['0'],
            ],
            LTR: [
                ['.8'], // monthly rent as percent of home value
                ['1000'],
                ['3000'],
                ['0'],
                ['3'],
            ],
            STR: [
                ['100'],
                ['300'],
                ['300'],
                ['3'],
                ['85'],
                ['95'],
                ['80'],
                ['5'], // averaged nights stay per guest
            ],
            FNF: [
                ['0'],
                ['0'],
                ['0'],
                ['0'],
                ['3'],
                ['6'], // percent agent commission
                ['0'],
            ]
            // TIME: [
            //     ['3'],
            //     ['2'],
            // ],
        },
        PURCHASE: [
            ['Downpayment (%)'],
            ['Downpayment ($)'],
            ['Closing costs ($)'],
            ['Estimated repair/furnish costs ($)'],
            ['Other lender costs ($)'],
        ],
        LOAN: [
            ['Loan interest rate (%)'],
            ['Points charged'],
            ['Loan term (years)'],
        ],
        EXPENSES: [
            ['Annual property taxes (% of home value)'],
            ['Annual property taxes ($)'],
            ['Insurance per year (% of home value)'],
            ['Insurance per year ($)'],
            ['Repairs & maintenance (% of monthly rent)'],
            ['Repairs & maintenance ($/month)'],
            ['Capital expenditures (% of monthly rent)'],
            ['Capital expenditures ($/month)'],
            ['Management fees (% of monthly rent)'],
            ['Utilities ($/month)'],
            ['HOA Fees ($/month)'],
            ['Other expenses ($/month)'],
        ],
        LTR: [
            ['Rental income (% of home value)'],
            ['Min rent ($/month)'],
            ['Max rent ($/month)'],
            ['Other income ($/month)'],
            ['Vacancy (%)'],
        ],
        STR: [
            ['Min nightly rate income ($)'],
            ['Max nightly rate income ($)'],
            ['# of nights available for booking per year'],
            ['Platform fee (% of gross rent charged)'],
            ['Cleaning cost ($/booking)'],
            ['Cleaning charged to guest ($/booking)'],
            ['Average occupancy rate (%)'],
            ['Average guest stay duration (days)'],
        ],
        FNF: [
            ['Desired profit ($)'],
            ['Closing costs ($)'],
            ['Repair costs ($)'],
            ['Holding costs ($/month)'],
            ['Holding time before sale (months)'],
            ['Agent commission at sale (%)'],
            ['Sale closing costs ($)'],
        ],
        // TIME: [
        //     ['Annual income growth (%)'],
        //     ['Annual expense growth (%)'],
        // ],
        LABELS: {
            PURCHASE: 'Purchase values',
            LOAN: 'Loan values',
            EXPENSES: 'Expenses',
            LTR: 'Long term rental values',
            STR: 'Short term rental values',
            FNF: 'Fix and flip values',
            // TIME: 'Time dependent values',
        },
        ORDERED_KEYS: [
            'PURCHASE',
            'LOAN',
            'EXPENSES',
            'LTR',
            'STR',
            'FNF',
            // 'TIME',
        ], // these must be in the same order as they appear on the setting sheet
        ANALYSIS_KEYS: {
            PURCHASE: [
                'downPaymentP',
                'downPaymentD',
                'closingCostsD',
                'estRepairCostsD',
                'otherLenderCostsD',
            ],
            LOAN: [
                'loanInterestRateP',
                'points',
                'loanTermYears',
            ],
            EXPENSES: [
                'propTaxesP',
                'propTaxesD',
                'homeInsuranceP',
                'homeInsuranceD',
                'repairsAndMaintP',
                'repairsAndMaintD',
                'capExP',
                'capExD',
                'managementFeesP',
                'utilitiesD',
                'hoaFeesD',
                'otherExpensesD',
            ],
            LTR: [
                'rentalIncomeP',
                'minRentD',
                'maxRentD',
                'otherIncomeD',
                'vacancyP',
            ],
            STR: [
                'minNightlyRateD',
                'maxNightlyRateD',
                'availableDaysPerYearForBooking',
                'platformFeeP',
                'cleaningCostD',
                'cleaningChargeD',
                'occupanyRateP',
                'avgStayDuration'
            ],
            FNF: [
                'desiredProfitD',
                'purchaseClosingCostD',
                'repairCostsD',
                'holdingCostsD',
                'holdingTimeMonths',
                'agentCommissionP',
                'fnfSaleClosingCostsD',
            ],
            // TIME: [
            //     'annualIncomeGrowthP',
            //     'annualExpenseGrowthP',
            // ]
        }
    },
    SETTINGS_NOTE: 'All settings and values are optional. Fill them out for defaulting the calculations.',
    ANA_SHEETNAME: String.fromCodePoint(0x1F4C8) + 'Properties to analyze',
    FREE_FEATURES: ["600 free GRE vocabulary words",
        "Review up to 10 flashcards per set",
        "Make up to 18 printable flashcards to Google Docs",
        "Add up to 5 images per flashcard set",
        "Create & add your own custom lists",
        "Add synonyms and mnemonics",
        "Add words to a 'Forgotten' set for re-review",
    ],
    PRO_FEATURES: ["Everything in Free tier plus...",
        "Review unlimited flashcards per set",
        "Create unlimited printable flashcards to Google Docs",
        "Add unlimited images",
    ],
    ELITE_FEATURES: ["Everything in Pro tier forever, plus...",
        "Unlimited spaced repetition study",
        "->Customize your own intervals",
        "->Much easier to use than Anki",
        "Unlimited reverse flashcards review (Answer/Prompt)",
    ],
    STRIPE_BADGE: "https://s3.amazonaws.com/blueplanit.co/stripebadge.png",
    SUPPORT_PAGE: "https://tidisventures.com/google-workspace-addon-support",
    PRIVACY_PAGE: "https://flashcardlab.co/privacy-policy?policy=flashcard-lab",
    DEFAULT_LABELS: ['Price', 'Address'],
    HEADERS_RANGE: 'A1:B1',
    DOC_BASE_URL:'https://docs.google.com/document/d/',
    MODAL_TYPES: {
        EDIT_CARD: 'EDIT_CARD',
        CREATE_CARD: 'CREATE_CARD',
    },
    AMPLITUDE: {
        STARTED_TEST: "FCL: Clicked Start Test",
        MAKE_CARDS: "FCL: Clicked Make Flashcards",
        CLICKED_FLASHCARDS_DOC: "FCL: Clicked Flashcards Doc link",
        GEN_LIST: "FCL: Generated vocab list",
        VIEWED_PRICING_MODAL: "FCL: Viewed pricing modal",
        SHOWED_FEEDBACK_SURVEY: "FCL: Showed feedback survey",
        SUCCESSFUL_PURCHASE: "FCL: user purchased add-on",
        SAVE_IMAGE: "FCL: Saved image in card editor",
        ERROR: "FCL: An error occured.",
        CLICKED_MOBILE_LINK: "FCL: Clicked mobile app link in purchase modal",
        USE_KEYBOARD_TO_NAV: "FCL: User used keyboard to test",
        CLICKED_GENERATE_FLASHCARDS: "FCL: Clicked generate flashcards.",
        CLICKED_CREATE_FLASHCARDS: "FCL: Clicked create flashcards view from drawer.",
        SAVED_SETTINGS: "FCL: Saved settings.",
        CLICKED_SETTINGS: "FCL: Clicked settings"
    },
    SURVEY_URL: 'https://docs.google.com/forms/d/1NdplMuuC1u7a3OLfJMv71PZv0Q-Z1vU6tW1Hsdg7oqs',
    LISTING_URL: 'https://workspace.google.com/marketplace/app/flashcard_lab/934660656831',
    FREE_VERSION_COPY: 'You are using a free version. ',
}
