module.exports = {
    SERVER_ERROR_MSG: "An error occurred while connecting to the server. Please contact support at tidisventures@gmail.com.",
    PAYMENT_ERROR_MSG: "An error occurred with your payment. Please try again or contact support at tidisventures@gmail.com.",
    VIEW_ACT_CTA: 'See pricing.',
    LIGHT_RED_BERRY: "#FFCBCB",
    LIGHT_GREEN: "#93c47d",
    DARK_RED_BERRY: "#5f2120",
    SETTINGS_SHEETNAME: `Settings`,
    PRIVACY_PAGE: 'https://tidisventures.com/privacy-policy?policy=z-real-estate-calc-gsheets-addon-privacy-policy',
    SETTINGS_NOTE: 'All settings and values are optional. Fill them out for defaulting the calculations.',
    STRIPE_BADGE: "https://s3.amazonaws.com/blueplanit.co/stripebadge.png",
    SUPPORT_PAGE: "https://tidisventures.com/support?app=z-real-estate-calculator-support",
    TERMS: "https://tidisventures.com/terms-and-conditions?app=z-real-estate-calculator-terms",
    HEADERS_RANGE: 'A1:B1',
    AMPLITUDE: {
        OPEN_SIDEBAR: "ZRE_CALC: Opened sidebar",
        SELECTED_ANA_TYPE: "ZRE_CALC: Selected analysis type",
        CLICKED_CALC: "ZRE_CALC: Clicked calculate button",
        VIEWED_PRICING_MODAL: "ZRE_CALC: Viewed pricing modal",
        PURCHASED: "ZRE_CALC: Purchased add-on",
    },
    FREE_VERSION_COPY: 'You are using a free version. ',
    DISCLAIMER: 'Use of this calculator signifies your agreement to our Terms and Conditions and the terms here. The calculators found in the Z Real Estate Calculator add-on are designed to be used for informational and educational purposes only, and when used alone, do not constitute investment advice. Tidis Ventures LLC and the Z Real Estate Calculator add-on recommends that you seek the advice of a real estate professional before making any type of investment. The results presented may not reflect the actual return of your own investments. Tidis Ventures LLC is not responsible for the consequences of any decisions or actions taken in reliance upon or as a result of the information provided by these tools. Furthermore, Tidis Ventures LLC is not responsible for any human or mechanical errors or omissions. Tidis Ventures LLC is not responsible or liable for the accuracy, completeness, or suitability of the property details. You are responsible for confirming the property details are accurate, complete, and suitable for your use case.',
    APP_CODE: 'LOI_AUTO',
    APP_SOURCE_CODE: 'sheets_loi',
    APP_SLUG: 'bulk-loi-sender',
    APP_VARIANT: '',
    FUNC_TIERS: {
        NONE: 0,
        FULL_FUNC: 1,
        FULL_FUNC_SUB: 2,
    },
    MAX_COL_NUMBER: 26,
    LS_KEYS: {
        SETTINGS: 'settings_LOI_v1',
    },
    FREE_LOI_GEN_CAP_PER_SHEET: 100,
    FREE_MAX_COL_NUMBER: 4,
    FREE_MAX_LETTER: 'D',
    DEFAULT_FREE_DAILY_SEND_CAP: 10,
    MAX_GWORKSPACE_PREMIUM_SEND_CAP: 1500,
    USE_GOOGLE_DOCS_BATCH_CAP: 25,
    NO_ATTACH_BATCH_CAP: 50,
    TOTAL_JOBS_WARNING: 5000,
    TOTAL_JOBS_CRITICAL: 10000,
    SNACKBAR_AUTO_HIDE_DURATION: 10000,
}
