module.exports = {
    SERVER_ERROR_MSG: "An error occurred while connecting to the server. Please contact support at tidisventures@gmail.com.",
    PAYMENT_ERROR_MSG: "An error occurred with your payment. Please try again or contact support at tidisventures@gmail.com.",
    VIEW_ACT_CTA: 'See pricing.',
    LIGHT_RED_BERRY: "#FFCBCB",
    LIGHT_GREEN: "#93c47d",
    DARK_RED_BERRY: "#5f2120",
    HEADERS_RANGE: 'A1:B1',
    AMPLITUDE: {
        OPEN_SIDEBAR: "LOI_AUTO: Opened sidebar",
        CREATED_TEMPLATE: "LOI_AUTO: Created template",
        SELECTED_TEMPLATE: "LOI_AUTO: Selected template",
        SELECTED_DATA_SOURCE: "LOI_AUTO: Selected data source",
        MAPPED_PLACEHOLDER: "LOI_AUTO: Mapped placeholder",
        CREATING_LOIS: "LOI_AUTO: Start creating LOIs",
        CREATED_LOIS: "LOI_AUTO: Created LOIs",
        SENDING_LOIS: "LOI_AUTO: Start sending LOIs",
        SENT_LOIS: "LOI_AUTO: Sent LOIs",
        NAVIGATE: "LOI_AUTO: Navigate using footer button",
        CLICKED_HELP: "LOI_AUTO: Clicked help button",
        UPGRADE_CLICKED: "LOI_AUTO: Clicked upgrade button",
        ERROR: "LOI_AUTO: Error",
        REFRESHED_SEND_DATA: "LOI_AUTO: Refreshed send data",
    },
    FREE_VERSION_COPY: 'You are using a free version. ',
    APP_CODE: 'LOI_AUTO',
    APP_SOURCE_CODE: 'sheets_loi',
    APP_SLUG: 'bulk-loi-sender',
    APP_VARIANT: '',
    FUNC_TIERS: {
        NONE: 0,
        FULL_FUNC: 1,
        FULL_FUNC_SUB: 2,
    },
    MAX_COL_NUMBER: 26,
    LS_KEYS: {
        SETTINGS: 'settings_LOI_v1',
    },
    FREE_LOI_GEN_CAP_PER_SHEET: 100,
    FREE_MAX_COL_NUMBER: 4,
    FREE_MAX_LETTER: 'D',
    DEFAULT_FREE_DAILY_SEND_CAP: 10,
    DEFAULT_PREMIUM_DAILY_SEND_CAP: 100,
    MAX_GWORKSPACE_PREMIUM_SEND_CAP: 1500,
    USE_GOOGLE_DOCS_BATCH_CAP: 25,
    NO_ATTACH_BATCH_CAP: 50,
    TOTAL_JOBS_WARNING: 5000,
    TOTAL_JOBS_CRITICAL: 10000,
    SNACKBAR_AUTO_HIDE_DURATION: 10000,
}
